### ISSUE TITLE
Adding .lark files to the translation page

### ISSUE THREAD

**Issue by brucemartens** [Felienne/hedy#1109]

**Comment by teundemast** [comment]
I think the most convenient way to create a .lark file from translated keywords on the translation page, is to first create a yaml from these keywords (because there is already a structure for creating yaml files). And then, using a function which transforms a .yaml file into a .lark file. 
So my current approach is as follows.
First add a keywords folder to coursedata. Then give a translator the option to fill in the translation of keywords and download a yaml file from this. The translation page will then look as follows: 
<img width="771" alt="Capture" src="https://user-images.githubusercontent.com/36051227/141691541-987317d3-064f-4c5c-b811-534f7007e05b.PNG">
The yaml file will be structured as follows:
<img width="217" alt="Capture2" src="https://user-images.githubusercontent.com/36051227/141691738-f9a4e049-1b1b-4236-af12-37d0320ddea9.PNG">
This file will be the input for the following function (I am not sure yet when this function should be called):
<img width="465" alt="Capture1" src="https://user-images.githubusercontent.com/36051227/141691772-41667ca0-b224-4e4a-bdf1-49322900c50b.PNG">
The output will be a keywords-{lang}.lark file in the grammars folder. 

@Felienne do you think this approach is the best way to attack this? Do you foresee any roadblocks? 
I would love to have your feedback on this before implementing and possibly wasting a lot of time :)

**Comment by Felienne** [comment]
This to me seems a fine approach!

**Comment by Felienne** [comment]
> The translation page will then look as follows: <img alt="Capture" width="771" src="https://user-images.githubusercontent.com/36051227/141691541-987317d3-064f-4c5c-b811-534f7007e05b.PNG"> 

It might be slightly nicer if we remove the _ from the token names and name the lowercase, so print instead of _PRINT but that is not super important right now.

**Comment by teundemast** [comment]
Thanks for your reaction! That will not be much hustle I think, so that's going to be all right!

**Comment by Felienne** [comment]
Closed by #1310
