### ISSUE TITLE
[UI idea] Implement a 403 error page

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1161]
**Idea incl level**
I would like to have a 403 page when a user tries to visit a page he/she isn't allowed to visit; returning an unauthorized error. Currently we simply return a string "unauthorized" and the corresponding 403 error code. It would be nice to have a specific page for this error code, similarly to the already implement 404 and 500 error code pages. Which can be found in #992.

**Comment by eylu4090** [comment]
Hi, interested in picking this up! I was wondering if there are any particular places/instances where a 403 error should appear?

**Comment by TiBiBa** [comment]
Hi @eylu4090, awesome that you want to contribute to Hedy! The 403 error is thrown when a user is trying to access a page he/she isn't allowed to. For example, when a non-teacher is trying to view a class overview page. In this case we "throw" a 403, for which we still need a dedicated page. So only the page itself needs to be made. The 403 error is already thrown on several occasions in the code (however we currently don't return a nice template). You can take a look at #992 as that issue is very similar but then for a 404 error.

As for your second question, I will pass that one on to @Felienne if that's possible: will let you know!

**Comment by eylu4090** [comment]
@TiBiBa awesome thank you!  Looked through all the places where a 403 is thrown, and I believe that a dedicated 403 page isn't required in `auth.py` (it just needs to throw a 403 error as there is no redirection to another page) or any place that throws a 403 error that is NOT involved with a GET request. Let me know if this is not the case! 

I have some changes staged to be tested, but I need a way to login into an account in the development server on localhost, otherwise I run into 403 errors coming from `auth.py` as I require a login, or I get redirected to the login page. I've tried creating an account, but I believe working on the development server does not allow account creation or login to my knowledge. However, in order to test some of the changes, I would need some way to login to test `/programs`, `/classes`, `/classes/<classid>` GET requests. 

If you or @Felienne have some kind of method without launching on the live server or if there is some documentation detailing how to test as a teacher or a student, that would be awesome!

**Comment by Felienne** [comment]
> If you or @Felienne have some kind of method without launching on the live server or if there is some documentation detailing how to test as a teacher or a student, that would be awesome!

I love the idea of test accounts! I have created my own and I guess @TiBiBa has too but it would be good to have generic ones. Can you reach out to me over email (hedy@felienne.com) so I can give you the environment vars to connect to the test db? Even though it is a test database I feel a bit weird posting it all here.

**Comment by eylu4090** [comment]
@Felienne @TiBiBa PR #1344 is ready for review and addresses this issue! Would appreciate some feedback :)
