### ISSUE TITLE
[BUG] Sign-up is broken (not because of email sending)

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#1182]
**Describe the bug**
Sign-up does not work (not because the welcome email fails to send). The root cause seems to be that this commit: https://github.com/Felienne/hedy/commit/744bfbbf569a6149a8c27c662e44e9e7f3f1663c removes the "auth" class of the form which is used as in auth.ts

Currently, an attempt to sign up gives the error "Please enter a username" because no values of the form are passed to the front-end validation.

**Expected behavior**
The sign-up does pick up the username and all fields of the form and validates them correctly.

**Comment by TiBiBa** [comment]
I think it is bad practice to make the javascript form handling dependent on a classname. Would be better to use an `id` for this as classes are supposed to be used by multiple elements. I removed the class in the commit because also some form styling was created in `styles.css` on the `auth` class.

**Comment by boryanagoncharenko** [comment]
I agree and I wanted to make the minimal fix that will unblock me. Do you want to take this over and address it the way you believe it is best? I see you are making many cool changes to the front-end.

**Comment by Felienne** [comment]
Fixed by #1183
