### ISSUE TITLE
Add unit tests for parsing Dutch keywords 

### ISSUE THREAD

**Issue by teundemast** [Felienne/hedy#1212]
The unit tests for the different levels are now designed to parse English keywords. To test if parsing Dutch keywords works as well, these tests need to be redesigned or new tests should be added.

**Comment by teundemast** [comment]
Now tests for level 1 are designed like this: 
<img width="446" alt="Capture" src="https://user-images.githubusercontent.com/36051227/140816129-2e476a70-72df-442d-bc83-ae5511ed60e2.PNG">
If we would like to test if all tests also work for Dutch keywords, we think the best way to do this, is to design every test as in the following picture. All these tests will then be called for the English language and the Dutch language.  
<img width="472" alt="Capture" src="https://user-images.githubusercontent.com/36051227/140815981-b6c0a54a-154d-42af-abda-2b0fa4b064f9.PNG">
@Felienne do you think this is the right approach?

**Comment by Felienne** [comment]
Hi @teundemast!

Thanks for checking before implementing. I don't think it is feasible, because imagine what the tests would look like when we support all 17 languages we now have. That would not really be readable. I would say the nl version should be right "by construction" because we generate the grammar form the same files. Adding a few tests just to be sure that is is that case should be fine.
