### ISSUE TITLE
Keywords in the sidebalk should also be translated, just as the demo code

### ISSUE THREAD

**Issue by teundemast** [Felienne/hedy#1256]

**Comment by FlorisHessels** [comment]
Since this is done in the Yaml files, I would like to know if you, @Felienne, agree with these Dutch translations for the keywords:

![teun](https://user-images.githubusercontent.com/91470479/142026433-49f55269-ccf0-43db-8032-99e6afb20858.jpeg)

Then, I can change all the Dutch Yaml files accordingly.

**Comment by Felienne** [comment]
Hi all!

willekeurigewijze I guess is a bit weird because we use it for list access, like `print dieren at random` so I guess `willekeurig` is better. And it can always be changed right, because I assume we will use some sort of converter to grab the existing programs and translate those?

**Comment by FlorisHessels** [comment]
Okay that's fine, I will use `willekeurig` instead of `willekeurigewijze`. Furthermore, we are in the process of making such a converter for programs, but we cannot use this converter for the Yaml files. This is because for example not every 'if' in the text should be converted to 'als'. The picture down below depicts an instance where the 'if' should not be translated to 'als'.

![happy](https://user-images.githubusercontent.com/91470479/142030121-bb627580-4eba-4529-8510-3e44f8b4336d.PNG)

Do you think that this is just a rare occasion or is this a roadblock for a converter for the Yaml files, @Felienne?

**Comment by Felienne** [comment]
This is not a roadblock perse, it just means you will have to use the
parser to parse the code, then transform the tree and pretty print the tree.

**Comment by FlorisHessels** [comment]
Okay that's clear. I will resolve this issue whenver issue #942 is done.

**Comment by teundemast** [comment]
So for this issue we are adding a function to yaml_transform.py. But we need to import the file hedy_translation, which is in the root folder. But since the root folder is of course not a package, we think this is the only way to do so: 
<img width="174" alt="Capture" src="https://user-images.githubusercontent.com/36051227/144456977-d63147f1-7dfd-4fde-b10b-7f87e9400967.PNG">
Hardcoding the path is of course not feasible for the hedy site, so we are thinking of creating a new transformer file in the root folder. @Felienne do you think this is the right solution? Or are we missing a solution?

**Comment by Felienne** [comment]
I don't think I understand, can't you just do this?

![image](https://user-images.githubusercontent.com/1003685/144478684-39db86c7-7e1f-46f2-a531-2f8bd945bfd1.png)

hedy can be imported too from the main dir into yaml_transform.py?

**Comment by Felienne** [comment]
> Hi @Felienne, I don't think hedy can be imported into yaml_transformer. At least at our machines, can you import hedy into yaml_transformer?

Yeah no issue whatsoever for me! Not sure why that would not work for you.

![image](https://user-images.githubusercontent.com/1003685/144480797-ac356b4d-b3ef-485b-8b25-f5e61d50308a.png)

(Macos, PyCharm)

**Comment by teundemast** [comment]
Hmmm that's strange, I think it has to do something with Windows, because it does also work on Ubuntu. Anyway, we will find a way to work with it. Thanks!
