### ISSUE TITLE
[BUG] repeat (and other constructs) do not check var existance

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1323]
**Describe the bug**
print checks whether a variable it uses actually exists, f.e. here:

https://github.com/Felienne/hedy/blob/3f4dbab96e00e2c6d97f20bd810b2372fd3a0b5e/hedy.py#L1019

But other constructs like loops and ifs can also access vars and we do not check that, generating syntactically valid but not working Python code.

**Paste the Hedy code & level**
Level 9 (current alpha)

```
repeat x times
    eten is ask 'Wat wil je bestellen?'
    if eten is pizza
        print 'lekker'
    else
        print 'pizza is lekkerder'
```

**Add a screenshot (optional)**

![image](https://user-images.githubusercontent.com/1003685/142449297-99b3af33-75fb-4397-bd84-8398314db2ea.png)

**Expected behavior**
An undefinedvar exception should be thrown (which will happen if you call check_var_usage)

**Comment by Felienne** [comment]
@dolfein Hi! I think this might be an issue for you to pick up, the issue makes a clear plan (I think?) and it is quite related to better error messages

**Comment by Felienne** [comment]
Ok now I think about this a bit more than one second, maybe we should do this check in the var_access() rule and not in every construct that we support, that saves us code. So f.e. here: 

https://github.com/Felienne/hedy/blob/3f4dbab96e00e2c6d97f20bd810b2372fd3a0b5e/hedy.py#L850

And pf course for higher level transpilers too.

**Comment by dolfein** [comment]
Trying to run the below Hedy program on level 12, raises `UnquotedAssignTextException`, which is (currently) the expected behaviour as there is a test at level 12 (`test_assign_string_without_quotes`) that checks whether that exception is raised.
<img width="496" alt="image" src="https://user-images.githubusercontent.com/71043277/146451184-17934b73-e64e-4d1c-b1a9-ca68eaff9c04.png">

But other than no quotation marks, the mistake can also be a undefined variable:
```
felienne is 'Felienne'
name is felienne
print name
```

Now that I have added the variable check, it raises `UndefinedVarException`. 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/71043277/146452680-e9059fdf-5694-4450-92d3-7c26e9d64d4e.png">

I feel like since it is a new syntax rule, the current exception might be more helpful for children. But on the other side the undefined var exception also suggests the same, so maybe this is fine as well?
How do we want this (at least for now, until #832 is implemented)?

**Comment by Felienne** [comment]
> Trying to run the below Hedy program on level 12, raises `UnquotedAssignTextException`, which is (currently) the expected behaviour as there is a test at level 12 (`test_assign_string_without_quotes`) that checks whether that exception is raised. <img alt="image" width="496" src="https://user-images.githubusercontent.com/71043277/146451184-17934b73-e64e-4d1c-b1a9-ca68eaff9c04.png">
> 
> But other than no quotation marks, the mistake can also be a undefined variable:
> 
> ```
> felienne is 'Felienne'
> name is felienne
> print name
> ```
> 
> Now that I have added the variable check, it raises `UndefinedVarException`. <img alt="image" width="495" src="https://user-images.githubusercontent.com/71043277/146452680-e9059fdf-5694-4450-92d3-7c26e9d64d4e.png">
> 
> I feel like since it is a new syntax rule, the current exception might be more helpful for children. But on the other side the undefined var exception also suggests to put quotation marks (though not as explicit), so maybe this is fine as well? How do we want this (at least for now, until #832 is implemented)?

Hi @dolfein, is there a branch/PR for your changes? That makes it easier to discuss them, and would be a better place also to discuss this issue (so I can run the code and see the impact on other Hedy programs) but in without further info, this change looks ok for me (indeed until we have finished #832)

**Comment by dolfein** [comment]
The branch is [check_var](https://github.com/Felienne/hedy/tree/check_var), I will make the PR later today after I changed the tests.
