### ISSUE TITLE
[UI idea] Hedy bulb for Program Repair should have smaller hover area

### ISSUE THREAD

**Issue by fRedelaar** [Felienne/hedy#1378]
**Description**
This issue is based on MR #1364 , on a reviewcomment made by @Felienne. The hovering area should be smaller. This will be fixed by adjusting the SVG files that are currently being used. 

> Looks supernice, thanks!!
> 
> The only thing is that the "hitbox" around the bulb seems quite large left to right (macos, Chrome):
> 
> https://user-images.githubusercontent.com/1003685/143062602-86747950-283f-4d78-90c0-6a92a291d3c3.mov
> 
> Can we make that a bit smaller?
> 
> _Originally posted by @Felienne in https://github.com/Felienne/hedy/issues/1364#issuecomment-976793922_

**Comment by johannadekker** [comment]
Here are the renewed, cropped files that should decrease the hit box. The issue was that the .svg was unnecessarily broad. I cropped the files.

The third file includes some yellow color so that Hedy actually lights up! 
![Screenshot 2021-11-26 at 14 58 50](https://user-images.githubusercontent.com/90705403/143591922-99081def-bb8d-4b57-91b3-4078b4fa4e7b.png)

**Comment by fRedelaar** [comment]
Since MR #1410  has been merged, I'm closing this issue.
