### ISSUE TITLE
When a user is not logged in, and they have made a program, they are always send to Register

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#143]
This is confusing to kids that already have an account! Can we change the message to say something like: ...create an account or login if you already have an account?

![image](https://user-images.githubusercontent.com/1003685/107952015-7a737b00-6f99-11eb-925d-bb9034b27c68.png)

**Comment by fpereiro** [comment]
@Felienne indeed, we should change the message. Unfortunately this type of dialog only allows for one type of redirect, not two.

What we can do is to redirect to /login, which has quite visible the "No account yet? Create account" link. Would this be good enough or should we build a custom pop-up with options for /login and /signup, as well as cancel?

**Comment by Felienne** [comment]
I would propose we redirect to login, if they login with a non-existing username or email, redirect again to register (potentially with the email/username they filled out already there?)

**Comment by fpereiro** [comment]
We could redirect to login and if the credentials are wrong and there is no matching username, suggest in the red box that they might want to create an account. Security-wise it's not great, since it allows for a quick way to figure out if someone's username or email is already being used. It's not too different from what could be achieved by doing the same on the signup form, but it is easier.

Here's my proposal: if there are invalid credentials submitted on login, we add a button to suggest to create a new account, whether there is an account with that email/username or not. If they click on it, their email (or username) is populated already on the form. Would that work?

**Comment by Felienne** [comment]
> Here's my proposal: if there are invalid credentials submitted on login, we add a button to suggest to create a new account, whether there is an account with that email/username or not. If they click on it, their email (or username) is populated already on the form. Would that work?

I think that sounds reasonable, but I do want to see it in action with kids

**Comment by fpereiro** [comment]
Agreed. I'll go ahead with it then and we'll see what happens in action!
