### ISSUE TITLE
[Language idea] Introduce `in` in level 13

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1442]
Right now `and` and `or` are introduced in level 13. It makes sense to me that we'd also introduce `in` in combination with `if`.  In is already working and we use it in `for dier in dieren`, but it's never really explained anywhere that you can use it with if. Since `and` and `or` are quite simple concepts and are similiar to `in`, maybe we could introduce them together?

I was working on this code
```
food is ask 'What do you want to eat?'
if food is 'salad' or food is 'soup' or food is 'sandwich'
    print 'Thats healthy'
```
But it makes more sense to program:
```
healthy_food is 'salad', 'soup', 'sandwich'
food is ask 'What do you want to eat?'
if food in healthy_food
    print 'Thats healthy'
```

Another option is to allow: 
`if food is 'salad' or 'soup' or 'sandwich'`

Which very much resembles natural language, but I'm not sure about the coding/Python practicality of it all.

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

`in` already works from level 4!

The code you suggested is correct level 13 code, see here: https://hedycode.com/hedy/1b292bccdb844434853453fe7438ef9b/view

`in` is regular Python code. I really like your second suggestion too with the `or`'s but that does not work at this point (we could add it but since we have the lists I would suggest to use that)

**Comment by MarleenGilsing** [comment]
Hi @Felienne, 

Great, I'll put it in the intropage for level 13 then and I'll add `in` to the try buttons as a new command (even though it already worked before).

**Comment by Felienne** [comment]
Yes it is a lovely idea to add it to the side bar!
