### ISSUE TITLE
Add suggestion to reset password on entry of wrong password

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#145]
![image](https://user-images.githubusercontent.com/1003685/107954060-451c5c80-6f9c-11eb-84eb-bec5a1cd4ba8.png)

Maybe in the red bar?

**Comment by fpereiro** [comment]
@Felienne Good idea! What about adding by default a "Forgot password" link below "Nog geen account", so that it is always visible in this view?

**Comment by Felienne** [comment]
It think that's the way we have it now, always visible?

![image](https://user-images.githubusercontent.com/1003685/107958659-9d565d00-6fa2-11eb-806f-cb23833b2f81.png)

The issue with that is:

1. it is in the way and distracts kids that do not need it
2. when kids do need it, it is not in the place that they are reading (in the red box)

I propose:
not visible initially, when they enter a wrong ww, if shows in the red box.

**Comment by fpereiro** [comment]
Let me add it to the red box, but still keep the other one. Compromise :).

If we take the existing link away, the only way that someone could find the "forgot password" would be to try with wrong credentials, which is not necessarily intuitive for everyone.

Virtually every application with login/signup has a link to "forgot password" at the bottom of the form, because users have learned to expect it there.

Would that be OK?

**Comment by Felienne** [comment]
Fine by me to have both, I think it will also all be a bit clearer if we use the same style for everything (now it "hangs" a bit loose as a link)

**Comment by fpereiro** [comment]
Agreed, I'll convert that link into a button as well!
