### ISSUE TITLE
Allow admin to see all programs

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#148]
Would be great if the Hedy/Admin user can see all programs, to aid in lessons. That saves kids with an issue from screensharing or copy-pasting programs to get help. It now shows:

![image](https://user-images.githubusercontent.com/1003685/107973597-af8dc680-6fb5-11eb-8376-2b0165d7ef31.png)

(This error message maybe for other users should be something like: "Unauthorized access" rather than "No such program"?)

**Comment by fpereiro** [comment]
We can definitely allow the admin user to look at all programs.

Regarding the 404 (not found) instead of a 403 (unauthorized), it's a security practice I saw implemented to give away as little info as possible - so if someone's trying to figure out if there's a program with id X that doesn't belong to them, they cannot tell whether it exists or not. I admit it's a bit silly to prevent randomly created IDs from being generated, but it is the application of a general security principle (it would be far less innocent if this referred to named documents or users, which is where the principle comes from). I can change it back to a 403 if you want :).

**Comment by Felienne** [comment]
Yeah you are right, it is somewhat of an exposure if we should that the program exists rather than it not being accessible to this user, so we can leave that as is.

But allowing the admin to see programs (and in the far future: allowing teachers to add kids to their class) would be great!
