### ISSUE TITLE
[UI idea] Indicate non-translated examples

### ISSUE THREAD

**Issue by nichtich** [Felienne/hedy#1605]
**Idea**
Several translations (e.g. Italian and German) don't include translation of all examples (Story, Turtle, ...), but the tabs of all examples are shown equally no matter whether translated or only in English. The interface could highlight these non-translated examples, e.g. with a superscript<sup>*</sup>, a popup hover message, and/or with another color. Students can choose to also try our English examples but these should not be mixed with localized examples by default.

This likely requires a new entry in `coursedata/texts/*.yaml` such as (`de.yaml`)

    only_in_english: "Bisher nur in Englisch verfügbar"

**Comment by Felienne** [comment]
Hi @nichtich,

Thanks for pointing this out, we are very much aware of open issues with the translation in many different aspects (See the corresponding [tag](https://github.com/Felienne/hedy/issues?q=is%3Aissue+is%3Aopen+label%3Atranslation), but luckily we have @Mark-Giesen: a new contributor who is going to pick the translation part up in the new year!

I like the idea of giving the tabs a different color, but of course ultimately, we would prefer for all content to be translated! That is the reason we show them in English instead of hding, so people see what is there and get enticed to translate. Maybe to strengthen that, we can also add a small link at the bottom with something like "translate this adventure" with a link to the translation UI (issue for @Mark-Giesen?)

Also, just a note but we aim for Hedy to be used in a classroom setting, and that is also how most people use it. And in that setting a teacher can choose to hide/show adventures so if they do not want to use the English translations, they can simply disable them. So the issue might be a bit smaller than you imagine.

Alternatively, we could also give teachers an extra tickmark if non-translated content should be hidden by default (maybe a small nice issue for @TiBiBa?)

**Comment by TiBiBa** [comment]
> Alternatively, we could also give teachers an extra tickmark if non-translated content should be hidden by default (maybe a small nice issue for @TiBiBa?)

I like the idea of an extra tick mark! Was also thinking about re-structuring the class customizations to better support changes like this later on. Currently we are only able to customize levels, but it would be nice if we also could customize the whole class at once (fixed language, hide non-translated adventures etc.)

**Comment by Mark-Giesen** [comment]
Sure @Felienne, that's an issue for me! When I start in februari, I'll browse issues en discussions to find ideas before I start designing.

**Comment by Felienne** [comment]
Fixed with the switch to Weblate!
