### ISSUE TITLE
Only one error shown and output screen not cleaned level-1

### ISSUE THREAD

**Issue by MarinusVanDijk** [Felienne/hedy#161]
![image](https://user-images.githubusercontent.com/37830964/108328283-b4789300-71cc-11eb-9b9b-b8933308a2af.png)

1. After run code button hit, the previous output is not removed if an error occurs.
2. The first line is in error, but the second is too. Only the second error is shown.

![image](https://user-images.githubusercontent.com/37830964/108328491-f30e4d80-71cc-11eb-8cb0-8b894959360b.png)

1. After run code button hit, the previous output is not removed if an error occurs.

**Comment by fpereiro** [comment]
Hi @MarinusVanDijk !

- I think it's intended to keep on showing the previous output in case an error is just inputted. In this way, the user still has the output of the previous working program as a guide to fix the current program.
- Showing one error at a time seems best to avoid cognitive overload. In the second case, it makes sense that "#print" is shown as an error since it's the first occurring error.
- It is indeed the case that if "ask" is entered without an argument on line 2, that takes precedence over the "#print" error on line 1. Probably some errors are given more priority than others. I'm not sure if this is by design or not - @Felienne does it make sense to change error reporting to be done starting with the first wrong line?

**Comment by Felienne** [comment]
Hi!

Indeed, it can be really helpful to see the error and the output at the same time, and indeed, processing two errors can be a bit hard to do for kids. And if it is a runtime error, Python will of course prevent us from showing the second error that could occur.

Since Timon is going to overhaul the error messages entirely, moving them to also be gradual, this can be closed for now.
