### ISSUE TITLE
Add percentage of errors to stats

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1668]
Now that we have stats, it is kind of hard to see what level is doing better/worse since they all have different bars:

![image](https://user-images.githubusercontent.com/1003685/149171648-e8d375ee-1d36-4cc4-9e16-0d78ebfd6b44.png)

Could we add a percentage in or above the bars, I think in the error ones makes the most sense?

**Comment by boryanagoncharenko** [comment]
Do you think want to see the absolute number of program runs per level and the error rate? For example, in the following image the left graph shows program runs (so that you see if a level got more program runs) and the right - the error rate per level.

![Screenshot 2022-01-13 at 9 25 15](https://user-images.githubusercontent.com/3010723/149284803-0f187dc9-7097-4c89-8c4c-70a7627d2aa2.png)

Or maybe you only need the graph with the error rate?

**Comment by Felienne** [comment]
I like the total numbers too, so this side by side would be great! I would also be happy with a textual representation by the way it does not have to be a graph, f.e. just 80% on top of/in the bar, like this:

![IMG_6268](https://user-images.githubusercontent.com/1003685/149300697-896f854e-1952-48f9-8914-fe499c7383f7.JPG)

**Comment by boryanagoncharenko** [comment]
As easy as it may seem to add the percentage values as annotations, I am afraid it is not easy to achieve. The closes thing that I could try doing is merge the 2 charts, so that there are 2 y-axes. The program runs bars will use the left y-axis and the error rate lines will use the right y-axis. Please note that I am not sure this is supported by the chart component because the bars are stacked while the error line should not be stacked. I will investigate.

Could there be a different way altogether to represent this data, so that it is convenient for you?

**Comment by boryanagoncharenko** [comment]
Just found that there is a plugin that supports adding data labels, so I will investigate briefly this option (timeboxed!)
