### ISSUE TITLE
[BUG] Comments are not allowed in all places

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1705]
We wrote comments to be mixed with other comments but not to be used *in* commands, like this:

```
choices is ['batu', 'kertas', 'gunting']
print 'Pilihlah'
print 'batu, kertas, gunting'
userc is ask 'Pilihan anda?'
print 'Pilihan anda: ' userc
computerc is choices at random
print 'Pilihan komputer: ' computerc
if userc is computerc:
    print 'SERI'
elif userc is 'batu' and computerc is 'kertas':
    print 'Komputer menang' #prints something <------ does not work now
else:
    print 'Komputer menang'
```

I guess rather than adding comments in the grammar as we do now, it would be easier to write a little preprocessor that removes all code on a line after the #. We already have preprocessing code in place, so that is not all too hard and we don't care about the comments anyway.

Maybe a fun issue for @racertop(when you are done with the input stuff, of course!)?

**Comment by racertop** [comment]
Hi! Yes, of course :)

**Comment by Felienne** [comment]
Hi @TiBiBa!

This could be your first grammar-related issue?

I would propose we approach it like this.

First make a test (what I do is simply copy an existing one and change it)

Then  In the level 1 grammar at such a rule:

`comment: "#" text`

should work, since text is more or less anything we support. Maybe we need to explicitly need to also allow comma and other stuff we disallow in text.

And then we can make `command` in `program` be `comment | command comment?` (a comment as separate command or a command optionally followed by a comment)

Let me know if you need further pointers!

**Comment by jpelay** [comment]
Hello! I'm working on a fix for this, similar to what you propose. This is what I've done so far:
1. Due to the grammar merger we can't change the command from a disjuntion to a distjuntion next to an alternation. So I did this on level 1 grammar:
```
command: print | ask | echo | turtle | comment | error_invalid_space | error_invalid
commandcomment: (command) (comment)*
```
Note that the comment rule is still allowed inside the command. 

2. Change the text rule on level one not to accept hash, otherwise on level 1 the print will take the text following the # as  normal text.

So now the tests pass for level 1, yay (except for lonely echo, I think thats because of the new command). On to level 2.

From now on we have to change the error rules so they exclude the #, same as we did on level 1. This still gives me problem sometimes due to ambiguity.

I've only covered levels 1, 2 and 3. On level 4 things will get complicated probably due to the strings.
