### ISSUE TITLE
[UI idea] Reset password for kid by teacher

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1736]
**Idea**

Some kids forget their password, but they can't access their email address (f.e. because they can't receive links or can't receive email outside of school) If would be great if teachers can set a password reset for this kid so that they can log in again. Once logged in, they can change their password again.

**Comment by TiBiBa** [comment]
I think this might be quite complex to implement when thinking about it. Do we want to give any teacher these privileges? Then we might want to add some checkbox when joining a class:

"When joining this class you accept that your teacher can reset your password".

Or do we want a bigger re-structure? Enabling children to create accounts without a mail address? Because they also need a mail account for sign up and verifying their account. If this is a recurring issue at schools we might want to re-think the way we create accounts. We can say: a teacher mail account can contain multiple accounts. But then we run into a lot issues in the back-end as we in general assume a mail / username is unique. This isn't necessary related to this issue as we can always implement the "Teacher can change passwords" functionality. But I think it would be nice to define our class direction to make sure it works best in the end.

**Comment by TiBiBa** [comment]
I think it would be best to wait until #1764 is merged until I start working on this. Otherwise, as they are very related we will run into a lot of merge issues later on.

**Comment by TiBiBa** [comment]
Will work on this today! I have this implementation in mind:

- Add a "reset password" column to the class-overview table
- Teacher get a modal.prompt and then a modal confirm
- Within the modal.prompt they can set a new password
- User logs in -> should reset password

Things to consider:

- Do we want to keep track of a "reset" account (boolean on user)? 
  -> We can navigate the user directly to change password on login
- Makes the implementation more complex but maybe more user-friendly
- Do we want to add a disclaimer to the "join class" page -> "You give the teacher access to blabla...."
