### ISSUE TITLE
[BUG] creating a variable from a variable in level 6 or higher

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1800]
When I run this code in level 6 or higher:

```
a is 10
b is a
print b
```
I get the unexpected result: 'a'

I expected the result to be 10, especially because this code:
```
a is 10
b is a + 1
print b
```
gives the result: 11

![image](https://user-images.githubusercontent.com/31697400/151032138-c4b3ada9-8180-4c81-9f10-ecaf778fb349.png)

**Comment by boryanagoncharenko** [comment]
It seems that this issue has been resolved. Tried it levels > 6 and it is correctly returning `10` instead of `a`:
<img width="1271" alt="Screenshot 2022-07-26 at 12 34 46" src="https://user-images.githubusercontent.com/3010723/180974762-cbdf7147-510b-4d16-8c6c-c808981e4a1c.png">

I am closing the issue, but please reopen it if the issue resurfaces again.
