### ISSUE TITLE
[UI idea] Don't show erroneous programs in explore

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1807]
If kids share a program that does not work, it will be shown in explore but it might not be a good example. Can we disallow that? We could either block the public sharing, or (better UX, but more expensive!) filter out erroneous programs when we populate explore.

**Comment by TiBiBa** [comment]
Agree! The best way might be to parse the code at the moment of sharing instead of the moment of retrieving the explore page. And return an error message in the case of a faulty program. However, students might also want to share a faulty program to their teacher to get help on debugging. We also have to set all programs to private first to make sure this works. Will think about a solution!

**Comment by TiBiBa** [comment]
We have to think about some other issues as well:

- What do we do with the current programs?
- Won't this be to expensive on the long run?

Current implementation idea:

- When saving - parse code
- If error -> show modal prompt "Are you sure you want to save this program with an error?"
- Set value "error: 1" on the program db
- Don't show programs with "error value" on /explore

However, there are currently (a lot) of programs containing errors due to the shifting of levels. We might have to parse all stored programs once more to add this error value.
