### ISSUE TITLE
[BUG] the naming constraint of variables - var cannot be a number - should be explained to students

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1992]
Given this program 

    123 is numbervar
    print 123

Students starting to learn programming are should learn to be aware that often variables starting with a number is not supported. 

Therefore, i thing this code should result in an error: ‘it looks like you are starting a variable name with a number which  is not allowed. A variable name must start with a letter’  
( partly true because emojis can also be used, but not in ‘real’ program languages)

![DEF7B503-A540-4C53-81BA-8AC2DF0E4AB7](https://user-images.githubusercontent.com/45706519/154140267-b32147cf-4d67-42af-ac95-5dcdecb04508.jpeg)

**Comment by Felienne** [comment]
Hi @ericverschoor!

It will be quite some work to actually make that nice error message, we would need an extra error production rule for this specific case, so I do not think we will do this, since it is a very uncommonly occurring error. Since we don't use anything like this in the examples, I think it is not very likely that a kid without a programming parent would try it

Plus, we can't have errors for all weird edge cases, there must be some explanation to do for parents/teachers :D
