### ISSUE TITLE
[BUG] lvl 4 print not results in an error

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1998]
Just to inform you of this strange behaviour

At lvl 4, using a print command with the `not` results in strange error.
This does not happen at lvl 3

    print not

results in an error:
![CBF298AC-5313-40F5-8DB3-B7648A5F1989](https://user-images.githubusercontent.com/45706519/154148930-c87367c4-dcff-4fd6-8cab-0f0fa55cc73a.jpeg)

**Comment by Felienne** [comment]
Yeah in fact this is as it should be, more or less. In level 4, you should use quotes, so with this code you are printing the variable `not` Because not is a keyword, it is hashed in the corresponding Python or the Python will not work, which is why you get the not so pretty error. We could map the variables back in the error message but that is quite some work. We are aware of the mapping issue so I am closing this one.

Hope that helps to understand it!
