### ISSUE TITLE
[BUG] error when using [+-*/] in quoted strings in level 6 and up

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2067]
This code works fine at level 6, but if you introduce an intermediate variable, then it doesn't work anymore.
```
print '3*10'
```
=> work
```
a is '3*10'
print a
```
=> a is not a Hedy level 6 command. Did you mean ask?

This code works correctly at level 5, but does not work from level 6

Moreover, we get the same error with the symbols + - / *

**Comment by thjazi39** [comment]
I think I made a mistake testing this, but now I realize that at level 6, assignments are not supposed to have quotes!

**Comment by boryanagoncharenko** [comment]
Level 6 assignments are, indeed, not supposed to have quotes. With the current version of the level 6 grammar the command `a is '3*10'` does not parse because '3*10' is not a text value (since it contains arithmetic operators) and it is not an arithmetic expression because the '3 and 10' are not valid arithmetic atoms.
Yet, if the Hedy user has previous programming experience this is a likely program to try (especially after quoted strings are introduced for ask and print commands in level 4). @Felienne what error do you think is best to give here?

**Comment by boryanagoncharenko** [comment]
I created a PR as a suggestion to resolve this issue and #2107 (since they are closely related). Please have a look at let me know if you agree: https://github.com/Felienne/hedy/pull/2211

**Comment by thjazi39** [comment]
ok, I tested the branch, and it works for me!
