### ISSUE TITLE
[BUG] Syntax highlighting sometimes breaks the front-end code

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2167]
**Describe the bug**
Currently the syntax highlighting sometimes seems to break due to a regular expression error. The bigger issue is that due to this error occurring all TypeScript code stops working. Resulting in a non-responding website where we can't switch levels, logout or have any other dynamic interaction. The problem seems to occur from level 3 and onwards and on specific programs (for example on the explore page). The following front-end error message seem to point to the problem:

![Schermafbeelding 2022-03-04 om 21 00 16](https://user-images.githubusercontent.com/38155424/156833228-85f4e53f-92f1-4087-bb9e-f0d8f2a9022d.png)

**Expected behavior**
Syntax highlighting should work fine on alle levels. When for some reason it doesn't work the error should be caught preventing the crashing of our complete front-end interaction.

**Comment by thjazi39** [comment]
I can't reproduce the bug, can you tell me more about the code used?

**Comment by TiBiBa** [comment]
> I can't reproduce the bug, can you tell me more about the code used and the language used (for the keywords and for the interface) ?
> 
> 
> 
> I tried to get a similar error in the browser console or in the python console, but after trying with Vivaldi and Firefox, and testing English/Dutch/French, I didn't see anything wrong (except for bug #2169, but that doesn't seem to match your definition. Especially since there is no error message that appears)
> 
> 
> 
> I suspect that a regex is not supported by your browser, can you tell me which one you use? (browser, version and OS) 

Hi! I was able to produce this error on Alpha. Safari, MacOS.

**Comment by thjazi39** [comment]
Ok, after some research with "Safari regex javascript", we find many similar problems

I have the impression that this is due to the fact that Safari doesn't respect the POSIX norma concerning some `Lookahead and Lookbehind` https://www.regular-expressions.info/lookaround.html (line 24 and 25 in syntaxModesRules.ts)

You can try with another browser (I think firefox should be available on mac) ?

**Comment by thjazi39** [comment]
I find it : https://writingjavascript.com/how-to-use-lookahead-lookbehind-in-regexp-in-javascript

**Comment by thjazi39** [comment]
Now that we know where it comes from, we have to solve the bug, and I confess that I don't know how to do it

I need to use the lookahead to simulate the function of "\b" (the start and end selectors of the word, but which are of zero length) and \b does not work in unicode.

Maybe by loading a specific module, which would allow Safari to support this ? or I can try to find another regex system, but the difficulty comes back to : "look at the characters around the keyword, without selecting these characters".

And I don't know how to do it without the lookahead

**Comment by Felienne** [comment]
Yeah I remember now that we have had this issue before with the lookbehind in Safari, are there does not seem to be a way to fix this in Safari, apart from doing it the way we did it before 😭

**Comment by Felienne** [comment]
We can revert the whole PR, or you can make a new one reverting only some of the changes that cause this problem (I don't really know how much of the work is affected)

**Comment by thjazi39** [comment]
So, I started today to try to solve this bug.
However, before trying to solve this bug, I would like to test the site under safari (to be able to test what is bugging, etc...)

But this is a problem, I spent the day trying to test different solutions to have access to safari, but I did not find any that works.
Because it would be too simple: Safari exists on Windows, but not on linux, so I can't test.

On Monday, I'll have to try to install virtual box on my computer, then put windows on it (because MacOs doesn't provide iso...) and then I'll be able to download the version of Safari for windows.
I don't know what it will do yet, but I feel like setting Virtualbox to access http://0.0.0.0:8080 will make it even funnier

If not, maybe there are some Mac or Windows machines available here, that I could use ? (but I think I'll need admin rights on the machine, if only to install the Hedy dependencies)

Translated with www.DeepL.com/Translator (free version)

**Comment by thjazi39** [comment]
Perfect !

**Comment by thjazi39** [comment]
Well, I tried the computer, it doesn't work. I tried to reinstall windows, but it doesn't seem to work (there's a shot that's broken, and there's a good chance that when the computer received the shot, it damaged the hardWare)

So I took the Windows option on Virtual Box, and I could have Safari, but now I have a new problem, I can't even open hedycode.com ... it doesn't seem to be a problem of the site, but rather of the browser (I have the same problem with wikipedia, problem that others have had)

Anyway, I'm still trying to solve the problem of porting to Safari, but I have to admit that Apple is pretty bad...

**Comment by thjazi39** [comment]
So, it works with Virtual Box, I can access the site 0.0.0.0:8080, the problem is that even on the main I do not have syntax highlighting...
This is due to the fact that Apple has stopped the development of safari for windows since 2012....
So, having another Windows computer will not allow me to test with this browser. I will need a computer under mac...

Apple does not provide official iso, I will try to find unofficial versions on the internet, so I can put it in VB

**Comment by TiBiBa** [comment]
I still have an old 2011 13" macbook pro. Not perfect, but it should work for some debugging and fixing.

**Comment by Felienne** [comment]
> I still have an old 2011 13" macbook pro. Not perfect, but it should work for some debugging and fixing.

ow that would be perfect, thanks a lot!!

**Comment by thjazi39** [comment]
Ok, thank you! 
For now I found a mac ISO on 01net, it's not very safe, but for now it seems to work on virtual box

**Comment by thjazi39** [comment]
That's it, I managed to test Hedy on Safari. The iso I found on O1net didn't work, obviously Apple did their best not to let me install macOS on anything else than apple hardware, but I found a script : https://github.com/myspaghetti/macos-virtualbox
Which allows to generate a machine for virtual box, and now it works !
So, I don't need to have a physical mac anymore, but thanks for the offer !

I can finally start debugging !
