### ISSUE TITLE
[BUG] Linguistic mix

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2169]
Trying the syntax highlighting with Dutch, I was surprised to find half the page in French (even in the same paragraph), English / Dutch / French keywords. (and I was suggested the language `ET` )

![image](https://user-images.githubusercontent.com/48509466/156872848-2d29c3b9-b570-4b13-8750-b5d93750cda9.png)

Moreover, the cursor does not appear at the right place: 

![image](https://user-images.githubusercontent.com/48509466/156872862-e3327a39-3e73-4133-b29f-1aa677a1df05.png)

In this screenshot, my cursor is in the middle of the t (which is already weird), but when I type a letter, I realize that I'm after the `@` at the end of the line.

You can also notice that the line numbers are badly displayed

**Comment by thjazi39** [comment]
I tested on several browsers, and it seems that this problem occurs only with Vivaldi (based on chrome)

**Comment by Felienne** [comment]
Hi @thjazi39!

Can you explain the steps that you took to get to this state? I am not sure what "Trying the syntax highlighting with Dutch" means?

**Comment by Felienne** [comment]
Ow wait a minute.... Did your Google translate maybe translate the website automatically? 

Because languages should be shown in their own language!! So Dutch should never be Neerlandais! It is always shown in Dutch (so: Nederlands):

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/1003685/156873972-e7803b79-87bf-4c00-9699-67653739368c.png">

**Comment by thjazi39** [comment]
Indeed, it was that! 
Thanks for the debug !

**Comment by Felienne** [comment]
Yeah I was like: how can you get in that very weird state haha?! Does that also explain the editor/cursor issues?
