### ISSUE TITLE
[BUG] Interpretation of quotation marks in level 9

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2186]
The quotes are interpreted when they are there, but they don't trigger any errors. So we have the following code, which has an output that should not be able to display both "You1" and "You2"

![image](https://user-images.githubusercontent.com/48509466/157468694-e2b25c7c-84fc-47c3-97b0-bcd68ad46183.png)

This prevents the interpretation of mark quotations in comparisons, as in the case of this code, which triggers an error:
```
var is I'm here # work now by #2129

if var is I'm here # not work with quote
  print 'Done !'
else
  print 'bouh !'
```

**Comment by huang-v** [comment]
What is the intended behavior for this level? Does this need to be addressed?

**Comment by huang-v** [comment]
Hi @Felienne,

I'm new to open source contributing and was wondering if this was a good first issue to work on or if it's even an issue to begin with?

**Comment by Felienne** [comment]
Hi @huang-v,

I must say I am not so sure myself about what the problem here is, or a solution direction, so I don't think this is a good issue. Have you checked our "good first issues": https://github.com/Felienne/hedy/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

These might be easier to do and beter scoped. I will have a look at the issues and tag you also where I think you can add value.

**Comment by Felienne** [comment]
@thjazi39, to clarify a bit already I removed your initial texts:

- there are quotation marks in the comparison of "if" (whereas it should be done only from level 12)
- there is a typo on the word scissors

Can you confirm these have indeed been fixed? I could not easily locate a corresponding PR since there are a few connected to #2129

**Comment by thjazi39** [comment]
I created this issue, because what is strange is that when we compare a variable with a string, the fact that there are quotes or not does not matter, which means that when we interpret the quotes in the `is`.

This is perhaps most telling with this example :
![image](https://user-images.githubusercontent.com/48509466/159944084-7673fce0-ef19-4082-9fb7-f45b1b7f1ffe.png)
```
var is I'm here

if var is I'm here
  print 'Done !'
else
  print 'bouh !'
```

**Comment by thjazi39** [comment]
> Can you confirm these have indeed been fixed? I could not easily locate a corresponding PR since there are a few connected to #2129

This is the same kind of error, but it is not in the assignment, but in the comparison.

I did the test on https://hedy-alpha.herokuapp.com/hedy/9 and it does not work, so it does not seem to be fixed

**Comment by Felienne** [comment]
> I created this issue, because what is strange is that when we compare a variable with a string, the fact that there are quotes or not does not matter, which means that when we interpret the quotes in the `is`.
> 
> This is perhaps most telling with this example : ![image](https://user-images.githubusercontent.com/48509466/159944084-7673fce0-ef19-4082-9fb7-f45b1b7f1ffe.png)
> 
> ```
> var is I'm here # work now by #2129
> 
> if var is I'm here # not work with quote
>   print 'Done !'
> else
>   print 'bouh !'
> ```

Ah ok that is a great concrete example! But indeed quotes are not mandatory until level 12 in equality checks, so that is expected and ok behaviour.

**Comment by Felienne** [comment]
> > Can you confirm these have indeed been fixed? I could not easily locate a corresponding PR since there are a few connected to #2129
> 
> This is the same kind of error, but it is not in the assignment, but in the comparison.
> 
> I did the test on https://hedy-alpha.herokuapp.com/hedy/9 and it does not work, so it does not seem to be fixed

This is getting too confusing, sorry. Can you open a fresh issue for the other things. And has the scissors typo been fixed? (otherwise fix that too or add an separate issue)

**Comment by boryanagoncharenko** [comment]
This issue touches upon 2 separate problems of the transpiler:
1) we intentionally remove the quotes around the right-hand-side text values in equality checks ([see here](https://github.com/Felienne/hedy/blob/main/hedy.py#L1067-L1070)). The end result is that it does not matter if you compare `rocket` or `'rocket'` because they will transpiler to the same
2) we do not escape inner quotes in the right-hand-side text values in equality checks. As a result, the transpiled code fails and we get the ugly 'bad input' error.

@thjazi39 can you confirm I the above description is correct? If so, don't think opening a second issue is needed because the 2 problems are tightly coupled.

@Felienne I encountered the problem of escaping quotes in text values (not quoted text but internal quotes like in `I'm done`) while working on the double quotes support and I was not able to come up with a proper solution. I tagged along the existing solution which is to strip all quotes, which of course is not great but ensures the correctness of the transpiled code. If there it is ok, I'd love to pick this up next week and combine it with the double quotes support.

**Comment by Felienne** [comment]
Yes, it would be great if you can pick this one up @boryanagoncharenko! You have the most comprehensive view of the current grammars!

**Comment by thjazi39** [comment]
> @thjazi39 can you confirm I the above description is correct? If so, don't think opening a second issue is needed because the 2 problems are tightly coupled.

So I don't know how the transpilator works, but what you say fits my problem!

**Comment by thjazi39** [comment]
> This is getting too confusing, sorry. Can you open a fresh issue for the other thing?
boryanagoncharenko summarized the situation about quotation marks very well.

> And has the scissors typo been fixed? (otherwise fix that too or add an separate issue)
Yes, it's okay, it's been fixed!

**Comment by boryanagoncharenko** [comment]
I did not think I would say it in the context of this issue, but this is not a bug, it is a feature!

The first problem mentioned in this ticket is that we intentionally remove the quotes around the right-hand-side text values in equality checks, so it does not matter whether we compare to `rocket` or `'rocket'` because they will transpiler to the same thing. This is a feature created as a workaround for levels 5 and 6 (see #1721 for reasoning). The summary is that at level 5 and 6 we don't want to enforce quotes in the right-hand-side of comparisons but, unfortunately, for parsing reasons we have to enforce quotes if the right-hand-side value contains spaces. So, if the right-hand-side does not contain spaces, quotes and no quotes are welcome, and if the right-hand-side contains spaces, then quotes are a must. The requirement for quotes around values with spaces is lifted in level 8 where a new line determines the end of the right-hand-side value. The transpiler continues supporting both quoted and un-quoted values up until level 12, which seems to be the correct behaviour.

This means that the focus of this issue will be escaping any quotes (single or double) in the right-hand-side of the comparison.

**Comment by boryanagoncharenko** [comment]
I created a PR to address the inner quotes in text values until level 12 causing 'bad input' error at runtime. Now I want to focus on solving the issue for the remaining levels.

Level 12 adds a particular challenge because the implementation of some commands uses f-strings (e.g. print and ask) and at the same time we add support for concatenation. Consider the following Hedy code and its transpiled version:
```
print "We " + "said: 'Hedy!'" # This Hedy code
print(f'{"We " + "said: Hedy!"}') # is transpiled to this Python code
```
Notice that the current implementation strips all inner single quotes from the transpiled code (around Hedy!). While this is done to preserve the correctness of the transpiled code, it is definitely something we need to address because it leads to unintended and basically incorrect output.

The issue is, I do not see how we could easily add the single quotes around Hedy! in the following python code `print(f'{"We " + "said: Hedy!"}')` since f-strings do not allow escaping. I think there are 2 options:
- Change the f-string quotes to ''' or """. This will address the usage of inner quotes but it will fail if the text value contains the same quote triplet used for the f-string. This feels more like a hack that will not address the problem but rather minimise the occurrences of errors.
- Move away from the f-string implementation, so that quotes can be escaped: `print('We ' + 'said: \'Hedy!\'')`. While this will address issue, it will end up in a rather big change.

My preferred solution is the second option, but since it will be an endeavour, I'd like to get your perspective before I dive into it. Maybe there is another solution that would not require a revamp of the implementations of the print and ask commands?

**Comment by boryanagoncharenko** [comment]
Discussed the issue with Felienne and decided to go with the first suggested approach. We will use ''' in the f-string and if a program tries to place ''' inside a text value, we will give an error that this is not supported.
