### ISSUE TITLE
"Program takes too long" error in early levels when using turtle

### ISSUE THREAD

**Issue by Tazaria** [Felienne/hedy#2554]
When working with the turtles in early levels, sometimes users want to make complicated drawings. Because the loops have not been introduced, they are forced to write multiple lines of code containing the same information. This can lead to programs with over 50 lines of code. This is not a problem in and of itself, but when the code gets executed Hedy sometimes thinks the code is taking too long and will exit with an error before the full picture is drawn. This can confuse and upset the user, as they technically did nothing wrong except make a too complicated program for the early levels to handle. 

One way to fix this would be to remove the too long error in early levels, as there is no way to get an infinite loop yet. Another way would be to extend the time before the error occurs. One user commented that the turtle moves at different speeds every run of the program, so sometimes the shape would complete and sometimes it would exit prematurely.

**Comment by Felienne** [comment]
Thanks for submitting this @Tazaria!

> One way to fix this would be to remove the too long error in early levels, as there is no way to get an infinite loop yet.

I think this is a very sensible suggestion! The only way that a program can take really long is if a user uses sleep with a high number, but then I guess it is clear? We can also block the use of numbers higher than a certain threshold with sleep.

**Comment by TiBiBa** [comment]
I will look into this! It might indeed be nice to remove the "too long" error on the lower levels. The only reason we implemented this is because the code is parsed server-sided but actually ran client-sided. If we don't limit the time a user might be able to crash their browser with a very long program: not really user-friendly. We already prevent very long programs on the server-side when parsing and maybe we don't want to restrict the user to much on the client-side usage.

One nice feature: skulpt has a built-in infinity loop detection and prevention, automatically terminating the program. We can look into this to set this parameter from a certain level. This might be a separate issue, but one we can look into as well. I think we should keep sleep as it is as. For now I propose the following:

- Remove "too long" error from levels 1 till 6 (as repeat is introduced in 7)
- Because we already have a line limit users will be unable to break their browser in these levels
