### ISSUE TITLE
[BUG] Keyerror should not break testsuite

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#2584]
**Describe the bug**
This code:
```
snippet[1].code = snippet[1].code.format(**keywords)
```` 
in both test_adventures.py and test_level_commands.py will result in a breaking error if a keyword in a snippet is accidently translated. In Arabic code both {is} and هو are allowed, but {هو} will result in this error.

**Comment by TiBiBa** [comment]
This is due to how the `format` function works. It's a dictionary that replaces all found keys with the corresponding values. So for Dutch the keywords dictionary would look like this: `keywords = {'print': 'print', 'echo': 'herhaal', 'ask': 'vraag'}`. The problem is, the function can't handle keys that don't exist. So in this issue the Arabic keyword does not exist as a key in the keywords dictionary (and crashes the program). We can look into catching these error, but best practice would be to use the English placeholders in all spots.

**Comment by TiBiBa** [comment]
We can to make sure always surround them with a specific try/except block. This has the advantage that we can specify in our prints on which blocks there are invalid placeholders, like this:

```
try:
    snippet[1].code = snippet[1].code.format(**keywords)
except KeyError:
    print("This following snippet contains an invalid placeholder ...")
```
