### ISSUE TITLE
[BUG] Text containing commas cannot be printed

### ISSUE THREAD

**Issue by remva** [Felienne/hedy#2695]
From level 4 and further, the following (or similar) code will give an error:

```sentence is "Hi, I'm Hedy"```
```print sentence```

"sentence" is labeled as a list, instead of text. Therefore it cannot be printed.

Solution: Commas in between apostrophes should create text and not lists.

**Comment by boryanagoncharenko** [comment]
As counter-intuitive as it may sound, this is not a bug, it is a feature.

In level 4 assignment does not require quotes, which means that the double quotes do not have any special meaning. They just happen to be the first character of the first list value and the last character of the second list value. This is a tricky scenario, which is why we added a [test](https://github.com/Felienne/hedy/blob/main/tests/test_level/test_level_03.py#L224-L233) to cover it.
