### ISSUE TITLE
[CONTENT] End Quiz having different language

### ISSUE THREAD

**Issue by Rezwin** [Felienne/hedy#2800]
**End Quiz having different language**

At level 7, the end quiz, questions number 8 and 9 has a different language when chosen language is English (Screenshot 1 & 3), this is reflected in both the result pages too (Screenshot 2).

**Screenshot 1**
<img width="1276" alt="Screenshot 2022-05-23 at 18 41 08" src="https://user-images.githubusercontent.com/98986856/169881768-82d46ca8-bcdc-401a-a0eb-ba4e11388a91.png">

**Screenshot 2**
<img width="1276" alt="Screenshot 2022-05-23 at 18 42 05" src="https://user-images.githubusercontent.com/98986856/169881885-e3503c27-4312-47a0-bf58-d5c7873eb7f9.png">

**Screenshot 3**
<img width="1276" alt="Screenshot 2022-05-23 at 18 42 29" src="https://user-images.githubusercontent.com/98986856/169882095-26ee1e92-ee50-42d9-8e45-cae013368290.png">

Thanks,
Rezwin

**Comment by TiBiBa** [comment]
Hi, thanks for making an issue for this! Will take a look into fixing this, it seems the Dutch and English translations got a bit mixed here.

**Comment by TiBiBa** [comment]
I just made a fix! Feel free to review the PR so we can merge this. Notice that when we merge the fix is first deployed onto our Alpha server, than after testing we deploy to the production server. This happens only around once a week so it might take some time before the fix is live on the hedycode.com website.
