### ISSUE TITLE
[UI idea] Error highlighting (level 4+)

### ISSUE THREAD

**Issue by arjank** [Felienne/hedy#2955]
**Level 4+: error highlighting**
When I try to execute code, it sometimes results in highlighting the entire line in red. But if the keywords on that line are not part of the problem, they will remain in their slightly different shade of red. That means the keywords are very hard to read. Of course this will resolve itself when you start editing the line, but it could be useful to see the entire line before you start editing.

Example when trying to run the code
`hal lo is 'wereld'`
![image](https://user-images.githubusercontent.com/457006/175394885-8526927f-5837-4cd5-aac3-69163f4dfc61.png)

**Comment by TiBiBa** [comment]
If I remember correctly this has something to-do with a line-by-line debugging that was once built for a student project. Showing the line that contains the actual error. But I can't recall what the exact reasoning behind the line highlighting was.

**Comment by arjank** [comment]
@TiBiBa I don't mind the highlighting, that part actually makes sense. But if keywords were a different colour, at least when the line is highlighted, they would be a lot easier to read.

**Comment by TiBiBa** [comment]
> @TiBiBa I don't mind the highlighting, that part actually makes sense. But if keywords were a different colour, at least when the line is highlighted, they would be a lot easier to read.

All right! I'm not sure what would be the best approach to solve this, I like the current color choices for the syntax highlighting as the nicely match the color scheme of the code editor. Might be best to make the line highlighter less intrusive, maybe through only showing a red border around the line or underlining the line. Do you want to pick up this issue? Otherwise I can take a look to make this more user-friendly.
