### ISSUE TITLE
[HIGHLIGHTING] Highlight color command in levels 2 to 10

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3053]
With the `color` command now available in levels 2 to 10 (#3051), we should change the highlighting accordingly

**Comment by thjazi39** [comment]
ok, this is not a problem for the color command.
But for the colors : 
- Either we consider that they are commands (and we color them in red)
- Or we consider them as constants (and we color them like the other variables, i.e. we do not color them)

I think it would be good not to color the names of colors, because when we code, we can manipulate the names of colors as variables (assignment in a variable, creation of lists, drawing, etc...)

**Comment by Felienne** [comment]
I see your reasoning about why not but I would suggest to color them, so we are consistent with `turn left` and color both:

![image](https://user-images.githubusercontent.com/1003685/180019165-b1ac9c19-01b2-4b94-9103-1d469723d898.png)

Or maybe we should give the colors and also left and right a different color? To indicate they are not commands but build-in contacts? I like that idea also.

**Comment by thjazi39** [comment]
I agree with the consistency with left and right, but the problem is not exactly the same either.

Left and right are only used in level 1, and in level 1 it is only used after the turn command. So it is very easy to "select" them with an automaton in order to highlight them in red (or green, orange or purple, that is not a problem)

On the other hand, colors are used until level 10, and in so many different contexts that it is much more complex.

Let's take for example this code that will work a quarter of the time:
```
list_col = blue, red, green, yellow bird

val is list_col at random

print val
color val
forward 50
```
The first 3 elements of the list are colors, but also text (we can display it) while the last element of the list, although containing the keyword yellow, is not a color.

In this case what should we do ?

By the way, like the other variables, it is possible to change the value of blue :
```
blue is test
print "variable blue : " blue # become "test"
color blue
```

**Comment by thjazi39** [comment]
So, I maintain that it is not necessarily a good idea to color the color names, because there are too many cases where it would be weird (like in https://hedycode.com/hedy/10#story or in the third code here https://hedycode.com/hedy/5)

And concerning the consistency with left and right, it would bother us as developers because we realize that it is the same thing: a predefined constant, but would the children find it inconsistent? (and since left and right are only at the first level, they probably won't have time to see this inconsistency) 

And in case the kids would find it incoherent, I would rather not color left and right anymore

**Comment by Felienne** [comment]
I understand your objections, but I insist we should place the colors and
left and right in one color category.

For now, let's make the color of that category white so it looks as if it
is not colored, that follows your suggestion of not coloring visually, but
also makes it trivial for me to color all either pink like keywords or a
different colors as constants if I want to.

Can you implement this within the new system or will you not have time
anymore?
