### ISSUE TITLE
[BUG] Remove language switcher in Ace window?

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#3322]
**Describe the bug**
Set Hedy in a non English language which has translated keywords (like Dutch). Now set the keywords to English in the code window. If you now choose an option from the Commands window, the keywords will be Dutch, not English. 

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/28646458/192157469-4256884c-ca13-4ee0-bc3f-cbad6464f36b.png)

**Expected behavior**
I expect the keywords to be English.

**Comment by TiBiBa** [comment]
These are intended to work separately. The dropdown within the code editor is only aimed for translating the current program.

If desirable we can look into implementing this as described in this bug. But atm not a bug but a design choice.

**Comment by Felienne** [comment]
Yeah I agree with @Mark-Giesen it is a bit confusing!

I think the right solution here is to get rid of the translator in the code editor, I will admit I just wanted to add it because it is so cool we can translate programs! Maybe we just show it when logged in as admin so I can continue to show it off?
