### ISSUE TITLE
[BUG] Can we enable search in Ace?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3342]
**Describe the bug**
Ace does not support search in Hedy at the moment, so if you hit ctrl-f nothing happens. Which is annoying in a long program

Can we enable it?

Maybe this will help: https://stackoverflow.com/questions/66681593/how-can-i-enable-the-search-box-in-an-ace-editor.

-------

Just a note for people also suffering from this until it is fixed: the browser can search, so if you click outside Ace, hitting ctrl-f does work:

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/1003685/192778356-28c12dc8-0513-4adc-b51a-c111fb2849f1.png">

**Comment by Felienne** [comment]
I added the tag good first issue because if we can just add the `editor.searchBox.show();` code it could be a one liner PR. But maybe it is more involved so don't worry if it is too hard.

**Comment by martinbeentjes** [comment]
Going to see if this is indeed a small change to implement, working on it. Hopefully I can get a PR ready.

**Comment by martinbeentjes** [comment]
Found the right file to implement this, need to understand Ace a bit, but event listener works. Which is a nice first step at the least. :tada:

**Comment by Felienne** [comment]
Great @martinbeentjes, awesome to see you so active!! If you need any help, let us know here or in Discord!

**Comment by martinbeentjes** [comment]
Going to see if I can take some time on Sunday to get it working. Searchbox extension doesn't seem to be available, I must be doing something wrong as it is an easy fix for sure. 

Fun second issue to work on!

**Comment by ToniSkulj** [comment]
> Going to see if I can take some time on Sunday to get it working. Searchbox extension doesn't seem to be available,

You are right @martinbeentjes! Turns out that the search functionality is builtin with the ACE editor. The only reason why it's not working is because the extension file **ext-searchbox.js** is missing. I found it here: [https://github.com/ajaxorg/ace-builds/blob/master/src/ext-searchbox.js](https://github.com/ajaxorg/ace-builds/blob/master/src/ext-searchbox.js). Added it to _/static/vendors_ and we can search away with ctrl+f 🔍 

![image](https://user-images.githubusercontent.com/48225550/195424221-88911d20-0892-4b83-85c0-02e6f97de86d.png)

The only thing troubling me is that it may look pretty daunting for kids (with all the search options). Maybe a more simplified version such as the one below?

![image](https://user-images.githubusercontent.com/48225550/195426430-7c7798b4-2317-4562-9e9a-19ab72bb299c.png)

Let me know!
