### ISSUE TITLE
[CONTENT] Answer question 7 incorrect for the quiz of level 8

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#3396]
The answer should be that you cannot use an `if` inside a `repeat` in level 8.

**Comment by sjensen19** [comment]
![image](https://user-images.githubusercontent.com/55716630/195425686-342c1fff-9355-4b15-8e51-ec7d6039dfa3.png)
![image](https://user-images.githubusercontent.com/55716630/195425728-64361694-b115-4d78-aa62-8031c9f70222.png)
@Felienne @OnnoEbbens Almost the same thing as #3401, but slightly different. In this case at question 7 repeat is not even used according to the YAML files inside the quiz folder. When looking at the quiz over on [hedycode.com](hedycode.com) it also does not show up as a question using the repeat statement

**Comment by sjensen19** [comment]
I could be completely wrong, but is it possible that it has something to do with using the beta or alpha version of the site? (I know some students actually use those instead of the main site)

**Comment by sjensen19** [comment]
After looking through the issues, I found #3351! It seems like this issue has been fixed there. As you can see in the screenshot below the repeat statement got replaced by the new question.
![image](https://user-images.githubusercontent.com/55716630/195427553-976ff495-4d08-4ca8-bc73-bc7b6d9f8bfa.png)

Think this issue is not relevant anymore... Still weird @OnnoEbbens experienced the fault 2 days ago. (Could be something to look into)
