### ISSUE TITLE
[UI, ADMIN] Improve UI of /admin/users

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3421]
**Idea incl level**
The admin interface (that only I use at the moment) could use a bit of love. I am grouping all issues here, if someone wants to pick up one, feel free to split out an issue!!

Firstly, this is what it looks like for me (not sure many people use it locally):

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/1003685/196131234-ac1e4d85-e34b-4bbf-9d83-73574fba88d1.png">

**1. Filtering (general)**

It is not possible to search for all fields, just a few. Would be nice to have them all, esp. the "is teacher" field/column, so I can ok them at once:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/1003685/196130805-c45d56e7-19a1-4c18-a496-b8198c653613.png">

**2. Filtering and pagination** 

We recently added pagination, but search seaches per page, so if I search for an old user, I have to click next next next. Not ideal.

**3. Filtering on non-English keywords**

I can search for users of 1 keyword language, but I am also interested to see all non-English users (maybe we'd want such an overview for the /admin/stats too)

~**4. Decline teacher request**~

Fixed by https://github.com/Felienne/hedy/pull/3427

**Comment by TiBiBa** [comment]
I will split point 4. first (as that seems the easiest one), will fix that right away!

**Comment by TiBiBa** [comment]
To add on this issue: For the filtering and pagination each filtering value should be implemented as a separate sort key in Dynamo, otherwise we will be unable to perform pagination. Currently we perform the filtering on the server after retrieval from Dynamo. This is inefficient as well, so point 1 and 2 should be fixed together with a re-write and adding of all the required keys. This is a bit more work than only coding:

- Implement within project
- Add sort keys to alpha db table
- Merge -> verify that it works
- Add sort keys to production db table

**Comment by Felienne** [comment]
Ah I guess we might need @rix0rrr's Dynamo expertise for this?

**Comment by Felienne** [comment]
Just discussed with @rix0rrr and it will be a bit too much work to only benefit me so we will leave this as is for now (I will write the queries in AWS 😅
