### ISSUE TITLE
[BUG] Creating students fails if 1 already exists

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3473]
**Describe the bug**

As reported on Discord: 
_"I'm creating a batch of student accounts all at once, entered some 30 names. Only to get an error saying "One or more account already exists"..._

_But it doesn't tell me which ones 😭"_

A quick fix of course is to highlight the one that exists in red and I think we at one point even had that working but it was somehow removed?

**Comment by TiBiBa** [comment]
> **Describe the bug**
> 
> As reported on Discord: _"I'm creating a batch of student accounts all at once, entered some 30 names. Only to get an error saying "One or more account already exists"..._
> 
> _But it doesn't tell me which ones 😭"_
> 
> A quick fix of course is to highlight the one that exists (which we should do an deploy soon) but I guess for the longer run is to make the usernames in the database with the class: student1@class5, but only show the first part in the UI, so we do not have too many clashes. As we are growing it might not be reasonable to expect all usernames in classes to also be unique?

The longer run solution would be an implementation nightmare. What if the class is deleted? The name of the class is changed? Or what if we have two identical class names with the same user? Because in our whole project we dependent on unique username for specific actions and verifications. We also allow the '@' in usernames so it would be hard to separate between these.

I agree that the current implementation has some limitations as multiple teachers simply want their students to have their surname as login. And I also don't have a clear idea on how we would best be able to tackle this issue.

**Comment by Felienne** [comment]
Yeah I agree it would be cumbersome, but we also want to make it as easy as possible for teachers, and it would be annoying if you cannot use usernames already in use. 

But let's maybe split that discussion into a separate issue indeed and make a solid plan, and then for now at least make sure the highlighting works (again, I think it did work at one point?)

Could you take a look what went wrong @TiBiBa?

**Comment by TiBiBa** [comment]
Will look into this right now!
