### ISSUE TITLE
UI/UX glitches

### ISSUE THREAD

**Issue by arjenpdevries** [Felienne/hedy#39]
UI/UX issues that you may not be able to solve, but good to know of:
1. Occassionally, after programs with errors were fixed, commands were executed twice. Do not know how to reproduce yet.
1. In Explorer / Edge, backspace is "back"; I ended up switching the kid to Firefox (they should do that anyways) because pressing backspace when Hedy does not have the focus caused him to loose his work time and time again, unrecoverable with "Forward" because state is not kept.
1. However, a child on a different (Linux) laptop and browser (FF) did seem to recover state.

**Comment by arjenpdevries** [comment]
4. Somehow, copy all, reload, paste, inserted an invisible character that also broke the code. The error mentioned some problem with `''` at the end of line 1.

**Comment by fpereiro** [comment]
Hi @arjenpdevries !

I think we're now past most of these issues!
1) We now prevent a program being executed twice by blocking the "run code" button while a prompt is being shown. We believe this fixes the issue.
2) We now prompt the user to save the program if navigating away from the page. This should prevent losing progress in IE.

Regarding 4), I'm not sure if it has been addressed since. @Felienne , do we happen have an issue open for non-ascii characters breaking the code?

**Comment by Felienne** [comment]
I think we did make a fix for non-ascii at one point, but this was before I was very organized with issues :) If the problem remains, best to make a new issue
