### ISSUE TITLE
Set up an alert service for when we experience downtime

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#462]
I was thinking of Pingdom or UptimeRobot. @rix0rrr , any suggestions?

**Comment by rix0rrr** [comment]
Heroku has built-in notifications:

![image](https://user-images.githubusercontent.com/524162/121022069-4fa86f00-c7a2-11eb-9b6d-691194d4381b.png)

It can send you emails when requests are taking a long time and/or there are too many failures. We could just enable those.

------------

Important rule of alerts to keep in mind though: **they should be actionable**.

If you're going to get an email, then go to the website and confirm that "*Yup, it's down*", and there's actually no remediation you can implement other than waiting for the event to be over... then what's the point of the added stress levels? 

I think we are equally well off periodically reviewing the metrics (let's say at the end of the day or every 2 days), and then when we see abnormal behavior log-diving and seeing if we can't determine the root cause and mitigate it for the future.

Yeah, it feels "fun" to be on-call and solve mysteries and Unbreak The World... but it also eats a lot of time and we should take care not to be distracted by it from other work.

-------

There's one case in which I think getting a notification might be potentially useful in our case: if we determine that our last code push was bad and it needs to be rolled back. That is an action an operator could take that could remedy a broken situation.

We should probably set the threshold fairly high before invoking that, and be rather sure an outage is due to bad code. That would mean: we only need to respond immediately if we get an alert and there has been a deployment within... oh let's say, the last 12 hours or so.

------

So conclusion: why not start with Heroku notifications, and make sure we only alert when latency is starting to hit something crazy like 20 seconds or 500 rate is hitting 25% ? And even then we only need to respond to it if it's likely the breakage is due to a fresh deployment.

**Comment by fpereiro** [comment]
@rix0rrr great points. Here's what I think:

- We should receive alerts when we have 500s, but I suggest setting a much lower threshold (1%). Ideally, we should have no 500 errors. A 500 should tell us that we have broken code. This is particularly useful after deployments. If we currently return 500s where we should return (say) 400s, I can change that right away.
- We should also get alerts when latency is really high (we could start with 20 seconds).

The idea is not to be jumping into things as they happen, but rather have a system that lets us know when things go bad so that we can then enable permanent fixes.

**Comment by fpereiro** [comment]
Done! Closing for now. If the alerts don't work, we can reopen the issue.
