### ISSUE TITLE
Unix line endings \r\n cause errors

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#53]
Example code:

naam is ask wat is de naam van de hoofdpersoon
print naam doet mee aan een race hij krijgt een willekeurige auto
auto is lamborghini, ferrari, porsche, honda
print auto at random

(not sure the line endings are preserved here but it will serve as a memory aid :))

**Comment by arjank** [comment]
This actually shows two issues. First there are the line endings, and once that is solved the second issue shows. (`\r\n` is the Windows line ending)

The transpiler considers `auto` is line 2 a variable name and does not add quotes around it. However the variable is only declared in line 3. So transpiling works, but code execution fails.

Also note that I'm assuming Level 2 here, because level 1 does not have groups and level 3 introduces quotes for literal words.
