### ISSUE TITLE
Show classes in profile

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#546]
For a normal (non-teacher) profile, show a list of classes in the profile page:

![image](https://user-images.githubusercontent.com/1003685/124380834-4fc35e00-dcbf-11eb-9479-f0bd37a720c6.png)

These do not have to be links or anything just for overview.

**Comment by Felienne** [comment]
Assigning this to myself because I want some layout tweaks

**Comment by Felienne** [comment]
@fpereiro We now place classes below the profile info, but teachers are going to use classes a lot more often than profile features. I designed it to the left (see drawing above) but I think above makes even more sense. Can you swap that?

I also think some rudimentary info on this page would be good: number of invites sent & number of invites accepted. Let me know if you want me to draw that also.

**Comment by fpereiro** [comment]
Hi @Felienne - I can indeed adjust the layout and add more detail. A few points:

- A drawing would be helpful because I don't know where specifically you'd like the box above (would it be to the left or right? Where would all the other parts of the profile fit? Or should I create a separate view altogether?)
- Regarding invites sent, we currently don't track that - an invite is simply a link sent by any means outside Hedy. We could, however, have the total number of students in the class in the preview (which would be equal to "invites accepted").

**Comment by Felienne** [comment]
Hi @fpereiro 

I thought about it more and I think we need to show this info in a separate page, combined with the teacher's manual so we have everything for teachers in one place. Profile (in retrospect) makes not all too much sense. 

I envision it like this:

![IMG_C2B0AB1E8E48-1](https://user-images.githubusercontent.com/1003685/130750207-8b4a4a2b-f70d-4d57-8d7d-8e45ed32fafc.jpeg)

This will entail:

* Moving the For Teachers page to be shown only when logged in as a teacher
* Moving the classes overview there (top of the page)
* Splitting the for-teachers.md in separate sections: generic, level1, level 2 etc.
* Showing a list of available sections
* Making them clickable so the text unfolds (like we had for Heyd docs waaaaaay bank!)

Let me know if this is clear enough

**Comment by fpereiro** [comment]
@Felienne Should we consider this closed after merging #694?

**Comment by Felienne** [comment]
Yes!
