### ISSUE TITLE
blank(_) in programs should get its own syntax highlighting

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#592]

**Comment by Felienne** [comment]
Ow and maybe this one is doable for you too @TiBiBa (would be a bit harder than the update to the existing rules because this needs a new strategy because _ can occur anywhere)

**Comment by Felienne** [comment]
Just though of this @TiBiBa, maybe you can pick this up with #1709

**Comment by thjazi39** [comment]
I'm currently working on syntax coloring, and I think it's quite possible to satisfy this issue.

It does require a little modification though, but it might help to standardize the conventions.
Indeed, in quizzes, since https://github.com/Felienne/hedy/pull/2019/commits/d1a964b0c2655d58e745336ae9ec7cc632213be4

blanks in programs are represented by the string `_?_`.

If it's ok with you, I can modify the `_` in the statements to make them follow the rules, and then adding syntax highlighting will be easier, since this sequence is "more complex" than just a `_`

**Comment by thjazi39** [comment]
I find 140 blank in all files in adventure (with `grep -Re "\b_\b" | wc -l` )
I will replace them with `_?_`

**Comment by Felienne** [comment]
> I find 140 blank in all files in adventure (with `grep -Re "\b_\b" | wc -l` ) I will replace them with `_?_`

Hmm I think I would prefer it the other way around, I find `_?_` a bit heavy in the snippets.

But why not both, they do serve different purposes? I think it is fine for the quizzes to keep `_?_` but snippets to have `_` or is there a reason that thay will make highlighting harder?

**Comment by thjazi39** [comment]
I understand better that the uses of the 2 strings are not exactly the same, so it's not necessarily a problem if there are 2 conventions that coexist (the syntactic coloring only has to recognize the 2 and we will use one or the other according to the context)

However, I still find that the underscore alone is maybe a bit too light or too common.
In the following example, I imagine a quiz where the goal is to find the writing of the `print` command, however, we will not be able to distinguish this case from a compound variable.

![image](https://user-images.githubusercontent.com/48509466/156563888-d723d222-712e-4ab7-b42f-449da0ea675c.png)

(the regex does indeed work with ``b_'', which detects the beginning and end of words, but as long as the underscore is not alone, it will not be detected)

a more 'exotic' symbol could solve this problem because there would be no need to look around

**Comment by thjazi39** [comment]
> > But we can also imagine a preprocessing during the interpretation, and which, if we detect this string, displays a message like "Attention, there are still holes to complete in the program".
> 
> We already do that:

Perfect!

Concerning the uniformity of the symbols, I noticed that in some files, the blanks were not `_` but `___` (2 or 3 underscores)

So I took some time to standardize this, I did it with the string `_?_` (in the blanks I found, in the whole race-data folder), but this is only temporary. If we find a better symbol for `_`, we can make the change in one shell command line, and if we want to keep only 1 underscore, then we can make the command to return to the underscore.

Knowing that if we want to apply one convention in quizzes, and another in adventures, then we just have to apply the (recusive) command further down the tree to have only the files we want to change.

I'll leave the branch aside, and if we ever use it, I'll make a PR :

https://github.com/Felienne/hedy/tree/uniformisation_blank_in_code

**Comment by Felienne** [comment]
> > > But we can also imagine a preprocessing during the interpretation, and which, if we detect this string, displays a message like "Attention, there are still holes to complete in the program".
> > 
> > 
> > We already do that:
> 
> Perfect!
> 
> Concerning the uniformity of the symbols, I noticed that in some files, the blanks were not `_` but `___` (2 or 3 underscores)
> 
> So I took some time to standardize this, I did it with the string `_?_` (in the blanks I found, in the whole race-data folder), but this is only temporary. If we find a better symbol for `_`, we can make the change in one shell command line, and if we want to keep only 1 underscore, then we can make the command to return to the underscore.
> 
> Knowing that if we want to apply one convention in quizzes, and another in adventures, then we just have to apply the (recusive) command further down the tree to have only the files we want to change.
> 
> I'll leave the branch aside, and if we ever use it, I'll make a PR :
> 
> https://github.com/Felienne/hedy/tree/uniformisation_blank_in_code

Ow great catch, I think we want to change all __ or ___ into _ for conformity. Can you make a PR for that?
