### ISSUE TITLE
spaces in between commands and text

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#857]
When you forget to use a space in between the command and text in level 4 the errors are unclear.

Some examples:
1.
`print'test'`

returns the error:

`The code you entered is not valid Hedy code. There is a mistake on line 1, at position 12. You typed , but that is not allowed.`

2.
`naam is ask'wat is je naam?'`

Does not give an error but creates a variable `naam` with the value `ask'wat is je naam?'`

3.
`naam is'test'`

returns the error:
`
naam is not a Hedy level 4 command. Did you mean ask?`

**Comment by Felienne** [comment]
1. is fixed in the grammar with a beter error message and clearer syntax highlighting
2. is really tricky because we allow assignment with `is` also. disallowing the use of `ask` in strings might lead to other problems
3. will be tricky to fix because <something> <space> <something else> matches our catch for all but I will think about how to do ti!

**Comment by Felienne** [comment]
Closing this, I suspect once we have program repair (will be soonish) to add spaces these will be fixed, so I don't want to spend separate effort on these
