### ISSUE TITLE
Add comments to a lower level

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#885]
In level 4 my students start to write long pieces of code >25 lines. Debugging is a lot harder if you don't have the option to use comments (`#`). Now comments are introduced in level 15, I think it would be nice to add them to an earlier level maybe between level 3 and 4.

**Comment by Felienne** [comment]
This is a great point @OnnoEbbens. The fix is easy to do, of course, but the deeper problem is how to teach comments. Do we do this in an entire level on its own as we have now? That does not really fit DG6 because it does not really allow kids to build more interesting programs because it does not give more expressive power.

Potentially, we could make a level specifically about the practice of debugging, using comments not only as a way to describe code but also to turn code on and off. In that level we can seed all adventures with errors kids have to fix? Would be a really good skill to have and we see kids lacking there. What do you think? (also tagging @MarleenGilsing to think about this)

**Comment by Felienne** [comment]
I just created #1261 allowing comments from level 1, so we can always use them, and teaching/using them is at the discretion of the teacher.

This of course does not yet address a "debugging level" which I still think is a great idea but I will make a separate issue, and also I think we will start with that when all other lang features (like https://github.com/Felienne/hedy/discussions/1207 and https://github.com/Felienne/hedy/discussions/1250 are closed)
