### ISSUE TITLE
Forgotten indent could get a better error message

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#930]
e.g. at level 7:

```
print 'kassabon'
prijs is 0
repeat 7 times
ingredient is ask 'wat wil je kopen?'
if ingredient is appel
prijs is prijs + 1
print 'Dat is in totaal ' prijs ' euro.'
```

![image](https://user-images.githubusercontent.com/1003685/136656458-223032d6-7241-4d85-98de-2cabcd609ede.png)

**Comment by remva** [comment]
Whenever you start a block with 3 spaces (for example), every block should start with 3 spaces to be correct. But the explanation at the top of level 7 says: "... That means putting four spaces at the beginning of the line.". 
This means that a block can only start with 4 spaces. 

In this case, should the text at the top be changed to "start every block with the same number of spaces"? Or should the error message be changed to "Oops! You used 3 spaces instead of 4".
